#include "list.hpp"
#include <string>
#include <utility>
#include <iostream>
#include <numeric>
#include "decision_tree.hpp"
int main() {
    mipt::DecisionTree tree("\"is alive\"\n"
                            "[\n"
                            "    \"is phystech\"\n"
                            "    [\n"
                            "        \"is a student\"\n"
                            "        [\n"
                            "            \"ALIVE - IS_PHYSTECH - IS_STUDENT === STUDENTS (BY GROUPS IF YOU ARE NOT LAZY)\"\n"
                            "\n"
                            "            \"ALIVE - IS_PHYSTECH - NOT_IS_STUDENT === PROFESSOR\"\n"
                            "        ]\n"
                            "\n"
                            "        \"is selling you something\"\n"
                            "        [\n"
                            "            \"does say 'thank you' after every purchase\"\n"
                            "            [\n"
                            "                \"Alisher\"\n"
                            "\n"
                            "                \"Canteen saleswoman\"\n"
                            "            ]\n"
                            "\n"
                            "            \"does look for you in the shower\"\n"
                            "            [\n"
                            "                \"Tetya Zoya\"\n"
                            "\n"
                            "                \"does want to steal your food\"\n"
                            "                [\n"
                            "                    \"is already fried and eaten\"\n"
                            "                    [\n"
                            "                        \"A rat\"\n"
                            "\n"
                            "                        \"A cockroach\"\n"
                            "                    ]\n"
                            "\n"
                            "                    \"is the most known living creature in MIPT\"\n"
                            "                    [\n"
                            "                        \"Poltorashka\"\n"
                            "\n"
                            "                        \"Sobaken#443\"\n"
                            "                    ]\n"
                            "                ]\n"
                            "            ]\n"
                            "        ]\n"
                            "    ]\n"
                            "\n"
                            "    \"is a building\"\n"
                            "    [\n"
                            "        \"is a dormitory\"\n"
                            "        [\n"
                            "            \"is inhabited by a cat\"\n"
                            "            [\n"
                            "                \"is visited by Ded\"\n"
                            "                [\n"
                            "                    \"1ka\"\n"
                            "\n"
                            "                    \"6ka\"\n"
                            "                ]\n"
                            "\n"
                            "                \"NOT_IS_ALIVE - IS_A_BUILDING - IS_A_DORMITORY - NOT_IS_INHABITED_BY_A_CAT === OTHER DORMITORIES\"\n"
                            "            ]\n"
                            "\n"
                            "            \"is place of unknown things and events\"\n"
                            "            [\n"
                            "                \"does have some biologists inside\"\n"
                            "                [\n"
                            "                    \"Phystech.BIO\"\n"
                            "\n"
                            "                    \"is occupied by RTshniki\"\n"
                            "                    [\n"
                            "                        \"Microelectronics Building\"\n"
                            "\n"
                            "                        \"Digit\"\n"
                            "                    ]\n"
                            "                ]\n"
                            "\n"
                            "                \"does have library inside\"\n"
                            "                [\n"
                            "                    \"the main building\"\n"
                            "\n"
                            "                    \"is mainly known for canteen\"\n"
                            "                    [\n"
                            "                        \"suicide\"\n"
                            "                        [\n"
                            "                            \"KPM\"\n"
                            "\n"
                            "                            \"KSP\"\n"
                            "                        ]\n"
                            "\n"
                            "                        \"is one of the oldest buildings\"\n"
                            "                        [\n"
                            "                            \"Laboratory Building\"\n"
                            "\n"
                            "                            \"does allow you to sTudI EaNgLiSh\"\n"
                            "                            [\n"
                            "                                \"Phystech.Kvant\"\n"
                            "\n"
                            "                                \"is inhabited by physicians\"\n"
                            "                                [\n"
                            "                                    \"Hospital\"\n"
                            "\n"
                            "                                    \"Arctic\"\n"
                            "                                ]\n"
                            "                            ]\n"
                            "                        ]\n"
                            "                    ]\n"
                            "                ]\n"
                            "            ]\n"
                            "        ]\n"
                            "\n"
                            "        \"is a sport court\"\n"
                            "        [\n"
                            "            \"=== SPORT_COURTS (VOLLEYBALL, FOOTBALL, ETC.)\"\n"
                            "\n"
                            "            \"does shock you\"\n"
                            "            [\n"
                            "                \"Mathematical logic course with Evgeniy Dashkov\"\n"
                            "\n"
                            "                \"is associated with night-time debugging\"\n"
                            "                [\n"
                            "                    \"does have a chance of grading you with 16\"\n"
                            "                    [\n"
                            "                        \"Introduction to data structures course with Ilya Dedinsky\"\n"
                            "\n"
                            "                        \"Introduction to programming course with Sergey Babichev\"\n"
                            "                    ]\n"
                            "\n"
                            "                    \"is fascinating to listen\"\n"
                            "                    [\n"
                            "                        \"Mathematical Analysis course with Vadim Redkozubov\"\n"
                            "\n"
                            "                        \"is dirty\"\n"
                            "                        [\n"
                            "                            \"seedbed\"\n"
                            "\n"
                            "                            \"Analytical geometry course with Anna Petrovich\"\n"
                            "                        ]\n"
                            "                    ]\n"
                            "                ]\n"
                            "            ]\n"
                            "        ]\n"
                            "    ]\n"
                            "]");
    tree.guess();
    return 0;
}