Start ::= Expr

Expr ::= AddSubExpr
AddSubExpr ::= MulDivExpr {('+' | '-') MulDivExpr}*
MulDivExpr ::= PrimaryExpr {('+' | '-') PrimaryExpr}*
UnaryExpr ::= PrimaryExpr | UnaryOperator
PrimaryExpr ::= '(' Expr ')' | Identifier | Number | StringLiteral

Identifier ::= Letter (Letter | Digit)*
Number ::= Digit+
StringLiteral ::= '"' (Digit | Letter)* '"'

Digit ::= "regexp:[0-9]"
Letter ::= EngLetter | '_'
EngLetter ::= "regexp:[a-zA-Z]"


Statement ::= Expr | BlockStatement
BlockStatement ::= '{' ListOfStatements '}'


