name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install sfml
        run: sudo apt-get install libsfml-dev
        
      - uses: actions/checkout@v2
        with: 
          submodules: true
      - name: Generate build files using cmake
        run: cmake -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ .
      - name: Run make
        run: make
      - name: Run tests
        run: ./runUnitTests
